import React from 'react';
import styles from "./page.module.css";



const Pipeline = () => {
  return (
    <div className={styles.page}>Pipeline
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cupiditate voluptatibus obcaecati expedita dolore, consequatur esse eum eligendi repellat, veniam minima inventore laborum delectus at. Maxime voluptas voluptate atque rem eos aut corrupti vero corporis officiis harum quam placeat dolores, qui consectetur adipisci repellat, eius libero cupiditate. Quasi explicabo, nobis quidem nemo harum quos omnis soluta exercitationem mollitia accusantium eaque, commodi unde distinctio in beatae itaque ea quis ducimus labore blanditiis. Dignissimos veritatis odio exercitationem magni quisquam, saepe quam, velit corporis aliquid ullam modi aperiam in cupiditate soluta aliquam. Maxime vero minus voluptates sunt reprehenderit. Consequatur iste tenetur repudiandae labore ducimus at, impedit quis error. Fugit autem atque alias dolorum tempore dolore praesentium nemo magnam unde eligendi neque, aspernatur magni cupiditate maxime. Voluptatem cum quod vel. Labore veniam ipsam, nobis deserunt eum distinctio corrupti quam aperiam sed ex voluptatem itaque! Assumenda minus totam eligendi veritatis quae voluptatibus quisquam voluptatem quis! Quis, corporis voluptates laborum ullam, vel necessitatibus magni recusandae repudiandae nihil eaque temporibus voluptatum voluptas delectus, nisi asperiores. Repellat aspernatur hic unde, quam dolorem voluptates illo delectus quod harum blanditiis esse neque dignissimos facilis. Vitae dolorum ea dolorem sit quo nisi, quaerat accusamus quos ut facere reiciendis molestiae error odio, dignissimos molestias? Quas illo non, vel natus assumenda laudantium nihil sequi repellat porro sunt? Repellendus, molestiae deleniti. Necessitatibus sint nesciunt debitis animi optio consequuntur natus molestias excepturi, a nulla, aspernatur nobis quidem modi. Eum laudantium aliquid dolorum similique doloremque reiciendis. Sit, porro beatae voluptatibus velit distinctio aperiam dolore nam expedita inventore qui earum itaque magni enim perspiciatis fugit praesentium, libero illum! Alias pariatur, adipisci cumque fugiat quod eius molestias corporis facere magnam totam, facilis minima distinctio eum eos atque itaque veritatis quibusdam possimus. Iusto veritatis exercitationem culpa modi possimus architecto odio, similique facere obcaecati voluptatum quas quasi deleniti libero voluptas mollitia velit sed ipsum sapiente ab deserunt voluptate dolorum ut. Nostrum ratione, iure blanditiis repudiandae aperiam fugit! Odit omnis adipisci quo modi voluptatibus consequuntur debitis nemo iure illum iste explicabo labore accusantium ipsa, repudiandae, quia at alias. Aperiam voluptate minus quibusdam nam animi vitae deleniti, aspernatur fugiat hic cumque! Natus, illum!</p>
    </div>
  )
}

export default Pipeline